In [1]:
import radiomics
from radiomics import featureextractor  # This module is used for interaction with pyradiomics

In [2]:
# Instantiate the extractor
extractor = featureextractor.RadiomicsFeatureExtractor (force2D=True)

print('Extraction parameters:\n\t', extractor.settings)
print('Enabled filters:\n\t', extractor.enabledImagetypes)
print('Enabled features:\n\t', extractor.enabledFeatures)

Extraction parameters:
	 {'minimumROIDimensions': 2, 'minimumROISize': None, 'normalize': False, 'normalizeScale': 1, 'removeOutliers': None, 'resampledPixelSpacing': None, 'interpolator': 'sitkBSpline', 'preCrop': False, 'padDistance': 5, 'distances': [1], 'force2D': True, 'force2Ddimension': 0, 'resegmentRange': None, 'label': 1, 'additionalInfo': True}
Enabled filters:
	 {'Original': {}}
Enabled features:
	 {'firstorder': [], 'glcm': [], 'gldm': [], 'glrlm': [], 'glszm': [], 'ngtdm': [], 'shape': []}


In [3]:
#--- imagePath, maskPath = radiomics.getTestCase('brain1')
imagePath = r'C:\WORK\AXLE\benchmarks\bench-pyradiomics\sampledata-multisegment\int\p0_y1_r100_c0_roi1.dcm' # 'C:\WORK\AXLE\data\OUTPUT\p0_y1_r100_c0_INT.nrrd'
maskPath = r'C:\WORK\AXLE\benchmarks\bench-pyradiomics\sampledata-multisegment\seg\p0_y1_r100_c0_roi1.dcm' # 'C:\WORK\AXLE\data\OUTPUT\p0_y1_r100_c0_SEG.nrrd'
print (imagePath, maskPath)

C:\WORK\AXLE\benchmarks\bench-pyradiomics\sampledata-multisegment\int\p0_y1_r100_c0_roi1.dcm C:\WORK\AXLE\benchmarks\bench-pyradiomics\sampledata-multisegment\seg\p0_y1_r100_c0_roi1.dcm


In [ ]:
# *************** DEBUG
import SimpleITK as sitk
import numpy as np
I = sitk.ReadImage(r'C:\WORK\AXLE\benchmarks\bench-pyradiomics\sampledata-multisegment\int\p0_y1_r100_c0_roi1.dcm')
#print(I)
nI = sitk.GetArrayFromImage(I)
U = np.unique(nI)
U

In [4]:
result = extractor.execute(imagePath, maskPath)
print (result)




---GLCM---_calculateMatrix() 
 P_glcm= (204, 204) 
 self.symmetricalGLCM= True 






---GLCM---acor: 
 i.shape= (204, 1) 
 j.shape= (1, 204) 
 self.P_glcm= [[0.         0.         0.00242718 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.00242718 0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.00242718 0.        ]
 [0.         0.         0.         ... 0.00242718 0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]] 
 ac= [[1094231.14563107 1103773.06220096 1110375.9408867  1100078.44343891]] 






---GLCM---Contrast(): 
 i.shape= (204, 1) 
 j.shape= (1, 204) 
 i= [[1.000e+00]
 [6.700e+01]
 [8.600e+01]
 [8.700e+01]
 [1.310e+02]
 [1.480e+02]
 [1.500e+02]
 [1.680e+02]
 [1.830e+02]
 [1.970e+02]
 [2.000e+02]
 [2.020e+02]
 [2.130e+02]
 [2.260e+02]
 [2.570e+02]
 [2.620e+02]
 [2.820e+02]
 [2.900e+02]
 [3.150e+0

GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated





---GLCM---SumAverage() 
 Ng= 1885 
 kValuesSum.shape= (3769,) 
 kValuesSum= [2.000e+00 3.000e+00 4.000e+00 ... 3.768e+03 3.769e+03 3.770e+03] 
 pxAddy.shape= (1, 3769, 4) 
 pxAddy= [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  ...
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]] 
 sum(pxAddy)= 1.0 






---GLDM---calculateMatrix():1: 
 matrix_args= [array([[[ 257,  443,  552,  568,  478,  496,  607,  876, 1411, 1696,
         1723, 1774, 1612, 1433, 1174,  886,  758,  814, 1069, 1020,
          835,  730,  817,  924,  900],
        [ 257,  397,  414,  386,  418,  526,  622,  888, 1375, 1612,
         1773, 1718, 1782, 1641, 1238,  959,  786,  991, 1158, 1093,
          915,  730,  720,  764,  697],
        [   0,  353,  384,  431,  493,  662,  795,  982, 1228, 1407,
         1497, 1556, 1558, 1560, 1377, 1080, 1032, 1174, 1241, 1262,
         1012,  878,  946, 1033,  809],
        [   0,  290,  399,  568,  673,  830,  847,  900, 1027, 1030,
         1234, 1255, 1258, 1382, 152

In [ ]:
extractor.disableAllFeatures()
print('Enabled features:\n\t', extractor.enabledFeatures)

# Specify some additional features in the GLCM feature class
#---extractor.enableFeaturesByName (glcm=['Autocorrelation', 'Homogeneity1', 'SumSquares'])
extractor.enableFeaturesByName (glrlm=['ShortRunEmphasisAK', 'LowGrayLevelRunEmphasis'])

print('')
print('Enabled features:\n\t', extractor.enabledFeatures)

In [ ]:
result = extractor.execute(imagePath, maskPath)
print (result)